CREATE TABLE IF NOT EXISTS `wallet_transaction` (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  transaction_type INT NOT NULL,
  amount DOUBLE NOT NULL,
  metadata LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP, 
  FOREIGN KEY (user_id) REFERENCES user(id)
);
