// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apps

import (
	"github.com/google/wire"
	"github.com/kumin/AndPadDating/configs"
	"github.com/kumin/AndPadDating/handler/http/v1"
	"github.com/kumin/AndPadDating/infras"
	"github.com/kumin/AndPadDating/repos/mysql"
	"github.com/kumin/AndPadDating/services"
)

// Injectors from wire.go:

func BuildServer() (*HttpServer, error) {
	serverConfiguration := configs.NewServerConfiguration()
	mysqlConnector := infras.NewMysqlConnector()
	userMysqlRepo := mysql.NewUserMysqlRepo(mysqlConnector)
	userService := services.NewUserService(userMysqlRepo)
	userHandler := http_handler.NewUserHandler(userService)
	matchingMysqlRepo := mysql.NewMatchingMysqlRepo(mysqlConnector)
	matchingService := services.NewMatchingService(matchingMysqlRepo)
	matchingHandler := http_handler.NewMatchingHandler(matchingService)
	feedMysqlRepo := mysql.NewFeedMysqlRepo(mysqlConnector)
	feedService := services.NewFeedService(feedMysqlRepo)
	feedHandler := http_handler.NewFeedHandler(feedService)
	httpServer := NewHttpServer(serverConfiguration, userHandler, matchingHandler, feedHandler)
	return httpServer, nil
}

// wire.go:

var SuperGraphSet = wire.NewSet(
	ServerGraphSet,
)
