// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/kumin/BityDating/entities"
	mock "github.com/stretchr/testify/mock"
)

// FileRepo is an autogenerated mock type for the FileRepo type
type FileRepo struct {
	mock.Mock
}

// UploadFile provides a mock function with given fields: ctx, file
func (_m *FileRepo) UploadFile(ctx context.Context, file *entities.File) (string, error) {
	ret := _m.Called(ctx, file)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.File) (string, error)); ok {
		return rf(ctx, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.File) string); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.File) error); ok {
		r1 = rf(ctx, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFileRepo creates a new instance of FileRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileRepo {
	mock := &FileRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
