version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-14T18-51-57Z
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - /Users/minh/minio/data:/data
