version: "3.0"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    expose:
      - "9090"
    volumes:
      - .:/etc/prometheus
      - prom-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - db-data:/etc/grafana/provisioning/datasources


volumes:
  prom-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../tmp/data
  db-data:
